# Generated by Django 4.2.7 on 2025-10-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkround',
            options={'ordering': ['-check_date', 'check_time'], 'verbose_name': '점검 회차', 'verbose_name_plural': '점검 회차 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='checkround',
            unique_together={('check_date', 'check_time')},
        ),
    ]
